# Generated by Django 3.1.4 on 2021-05-26 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 15, 59, 41, 85714, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 15, 59, 41, 85714, tzinfo=utc)),
        ),
    ]
